<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?= $list_name ?> by thread</title>
<meta name="Subject" content="by thread" />
<meta name="robots" content="noindex" />
<link rel="stylesheet" href="/StyleSheets/Mail/public-messagelist.css" type="text/css" />
<link rel="alternate stylesheet" title="Shorter view" 
    href="/StyleSheets/Mail/style-short.css" />
<link rel="help" href="/Help/" />
<link rel="start" href="../" title="<?= $list_name ?> archives" />
</head>
<body>
<div class="head">
<map title="Navigation bar to upper levels" id="upper">
<p>
   <a href="//www.w3.org/">W3C home</a> &gt;
   <a href="../" title="Public Mailing lists">Public Mailing lists</a> &gt;
   <a href="./" title="Index of <?= $list_name ?>" rel="start"><?= $list_name ?></a> &gt;
</p>
</map>
<h1><?= $list_name ?> by thread</h1>
<map title="Navigation bar" id="navbar" name="navbar">
<ul>
  <li>
    <dfn>About this list</dfn>: 
    [ <a href="./threads.html" title="Messages index grouped by threads">Index by threads</a> ]
    [ <a href="./" title="Messages index grouped by calendar periods">Index by calendar periods</a> ]
  </li>
</ul>
</map>
</div>

<?php if ($newer): ?>
<nav class="next">
	<a rel="prev" href="<?= $newer['path'] ?>">Newer threads</a>
</nav>
<?php endif; ?>

<div class="messages-list">
<ul>
<?php foreach ($messages as &$message): ?>
<li><a href="<?= $message['path'] ?>"><?= htmlspecialchars($message['subject'], ENT_QUOTES) ?></a>&nbsp;<a><em><?= htmlspecialchars($message['author'], ENT_QUOTES) ?></em></a>&nbsp;<em>(<?= date_format($message['date'], 'l, d F Y') ?>)</em>
<?php endforeach; ?>
</ul>
</div>

<?php if ($older): ?>
<nav class="next">
	<a rel="next" href="<?= $older['path'] ?>">Older threads</a>
</nav>
<?php endif; ?>

<ul>
<li><dfn><a id="end" name="end">Last message date</a></dfn>: <em>Monday, 12 September 2016 10:43:19 UTC</em></li>
<li><dfn>Archived on</dfn>: Monday, 12 September 2016 10:43:20 UTC</li>
</ul>
<div class="foot">
<map title="Navigation bar" id="navbarfoot" name="navbarfoot">
<ul>
<li><dfn><a href="#first">35 messages</a> sort by</dfn>:
 [ thread ]
 [ <a href="author.html" title="Contemporary messages by author">author</a> ]
 [ <a href="index.html" title="Contemporary messages by date">date</a> ]
 [ <a href="subject.html" title="Contemporary messages by subject">subject</a> ]
</li>
</ul>
</map>
<!-- trailer="footer" -->
<p><small><em>
This archive was generated by <a href="http://www.hypermail-project.org/">hypermail 2.3.1</a>
: Monday, 12 September 2016 10:43:20 UTC
</em></small></p>
</div>
</body>
</html>


